ALTER TABLE inboxes ADD COLUMN IF NOT EXISTS folder_archive TEXT;
ALTER TABLE inboxes ADD COLUMN IF NOT EXISTS folder_sent TEXT;
ALTER TABLE inboxes ADD COLUMN IF NOT EXISTS folder_trash TEXT;
ALTER TABLE inboxes ADD COLUMN IF NOT EXISTS folder_spam TEXT;
